# Site settings
title: Emily Jade Darrow's Jekyll Portfolio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm putting all the coolest stuff I've ever done and links to all of my work here.
  I also maintain a heroku portfolio at http://apcentral.herokuapp.com/ejdarrow
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unarmed1618.github.io" # the base hostname & protocol for your site
twitter_username: unarmed1618
github_username:  unarmed1618

# Build settings
markdown: kramdown
