# Site settings
title: Emily's BlogFolio
email: ejdarrow@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  All the coolest stuff I've ever done.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unarmed1618.github.io" # the base hostname & protocol for your site
facebook_username: unarmed1618
github_username:  unarmed1618
twitter_username: unarmed1618

# Build settings
markdown: kramdown
